import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ConfigProvider } from "antd";

import { AntdRegistry } from "@ant-design/nextjs-registry";
import CommonHeader from "@/components/CommonHeader";
import CommonFooter from "@/components/CommonFooter";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <ConfigProvider
          theme={{
            token: {
              colorBorder: "#ffe60f",
            },
          }}
        >
          <AntdRegistry>
            <CommonHeader></CommonHeader>
            {children}
            <CommonFooter />
          </AntdRegistry>
        </ConfigProvider>
      </body>
    </html>
  );
}
